apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
  namespace: webserver
spec:
  type: LoadBalancer
  selector:
    app: webserver
    env: development
  ports:
  - name: http
    port: 80
    targetPort: 80

